export const products = [
  {
    title: 'Classic Oxford Shirt',
    description: 'Classic Oxford Shirt with a clean modern silhouette, comfortable fabric and versatile styling for everyday smart-casual looks.',
    category: 'shirts',
    price: { amount: 1899, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Premium Cuban Collar Shirt',
    description: 'Premium Cuban Collar Shirt with a clean modern silhouette, comfortable fabric and versatile styling for everyday smart-casual looks.',
    category: 'shirts',
    price: { amount: 2099, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Textured Resort Shirt',
    description: 'Textured Resort Shirt with a clean modern silhouette, comfortable fabric and versatile styling for everyday smart-casual looks.',
    category: 'shirts',
    price: { amount: 1999, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Linen Blend Shirt',
    description: 'Linen Blend Shirt with a clean modern silhouette, comfortable fabric and versatile styling for everyday smart-casual looks.',
    category: 'shirts',
    price: { amount: 2199, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Striped Casual Shirt',
    description: 'Striped Casual Shirt with a clean modern silhouette, comfortable fabric and versatile styling for everyday smart-casual looks.',
    category: 'shirts',
    price: { amount: 1799, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Relaxed Camp Collar Shirt',
    description: 'Relaxed Camp Collar Shirt with a clean modern silhouette, comfortable fabric and versatile styling for everyday smart-casual looks.',
    category: 'shirts',
    price: { amount: 1999, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Premium Check Shirt',
    description: 'Premium Check Shirt with a clean modern silhouette, comfortable fabric and versatile styling for everyday smart-casual looks.',
    category: 'shirts',
    price: { amount: 2099, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Solid Overshirt',
    description: 'Solid Overshirt with a clean modern silhouette, comfortable fabric and versatile styling for everyday smart-casual looks.',
    category: 'shirts',
    price: { amount: 2299, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Essential Black Tee',
    description: 'Essential Black Tee with a comfortable modern fit, premium feel and easy styling for everyday streetwear looks.',
    category: 't-shirts',
    price: { amount: 999, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Heavyweight White Tee',
    description: 'Heavyweight White Tee with a comfortable modern fit, premium feel and easy styling for everyday streetwear looks.',
    category: 't-shirts',
    price: { amount: 1199, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Graphic Street Tee',
    description: 'Graphic Street Tee with a comfortable modern fit, premium feel and easy styling for everyday streetwear looks.',
    category: 't-shirts',
    price: { amount: 1299, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Minimal Logo Tee',
    description: 'Minimal Logo Tee with a comfortable modern fit, premium feel and easy styling for everyday streetwear looks.',
    category: 't-shirts',
    price: { amount: 1099, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Essential Grey Tee',
    description: 'Essential Grey Tee with a comfortable modern fit, premium feel and easy styling for everyday streetwear looks.',
    category: 't-shirts',
    price: { amount: 999, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Studio Black Tee',
    description: 'Studio Black Tee with a comfortable modern fit, premium feel and easy styling for everyday streetwear looks.',
    category: 't-shirts',
    price: { amount: 1199, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Graphic Print Tee',
    description: 'Graphic Print Tee with a comfortable modern fit, premium feel and easy styling for everyday streetwear looks.',
    category: 't-shirts',
    price: { amount: 1299, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Urban Street Tee',
    description: 'Urban Street Tee with a comfortable modern fit, premium feel and easy styling for everyday streetwear looks.',
    category: 't-shirts',
    price: { amount: 1199, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Relaxed Cargo Pants',
    description: 'Relaxed Cargo Pants designed with a contemporary silhouette, comfortable construction and versatile styling for everyday outfits.',
    category: 'bottoms',
    price: { amount: 2299, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Straight Fit Denim',
    description: 'Straight Fit Denim designed with a contemporary silhouette, comfortable construction and versatile styling for everyday outfits.',
    category: 'bottoms',
    price: { amount: 2499, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Utility Trousers',
    description: 'Utility Trousers designed with a contemporary silhouette, comfortable construction and versatile styling for everyday outfits.',
    category: 'bottoms',
    price: { amount: 2199, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Wide Leg Pants',
    description: 'Wide Leg Pants designed with a contemporary silhouette, comfortable construction and versatile styling for everyday outfits.',
    category: 'bottoms',
    price: { amount: 2399, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Classic Black Jeans',
    description: 'Classic Black Jeans designed with a contemporary silhouette, comfortable construction and versatile styling for everyday outfits.',
    category: 'bottoms',
    price: { amount: 2599, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Grey Denim Cargo Pants',
    description: 'Grey Denim Cargo Pants designed with a contemporary silhouette, comfortable construction and versatile styling for everyday outfits.',
    category: 'bottoms',
    price: { amount: 2499, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Printed Wide Pants',
    description: 'Printed Wide Pants designed with a contemporary silhouette, comfortable construction and versatile styling for everyday outfits.',
    category: 'bottoms',
    price: { amount: 2299, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Classic Blue Jeans',
    description: 'Classic Blue Jeans designed with a contemporary silhouette, comfortable construction and versatile styling for everyday outfits.',
    category: 'bottoms',
    price: { amount: 2499, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Drop Shoulder Oversized Tee',
    description: 'Drop Shoulder Oversized Tee designed with a relaxed oversized silhouette, comfortable fabric and modern streetwear styling.',
    category: 'oversized',
    price: { amount: 1399, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Washed Oversized Hoodie',
    description: 'Washed Oversized Hoodie designed with a relaxed oversized silhouette, comfortable fabric and modern streetwear styling.',
    category: 'oversized',
    price: { amount: 2499, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Streetwear Oversized Shirt',
    description: 'Streetwear Oversized Shirt designed with a relaxed oversized silhouette, comfortable fabric and modern streetwear styling.',
    category: 'oversized',
    price: { amount: 1999, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Heavyweight Oversized Tee',
    description: 'Heavyweight Oversized Tee designed with a relaxed oversized silhouette, comfortable fabric and modern streetwear styling.',
    category: 'oversized',
    price: { amount: 1599, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Oversized Graphic Tee',
    description: 'Oversized Graphic Tee designed with a relaxed oversized silhouette, comfortable fabric and modern streetwear styling.',
    category: 'oversized',
    price: { amount: 1499, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Urban Oversized Hoodie',
    description: 'Urban Oversized Hoodie designed with a relaxed oversized silhouette, comfortable fabric and modern streetwear styling.',
    category: 'oversized',
    price: { amount: 2399, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Black Street Hoodie',
    description: 'Black Street Hoodie designed with a relaxed oversized silhouette, comfortable fabric and modern streetwear styling.',
    category: 'oversized',
    price: { amount: 2299, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Graphic Oversized Hoodie',
    description: 'Graphic Oversized Hoodie designed with a relaxed oversized silhouette, comfortable fabric and modern streetwear styling.',
    category: 'oversized',
    price: { amount: 2499, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Premium Satin Shirt',
    description: 'Premium Satin Shirt crafted for a refined premium look with elevated detailing, modern tailoring and versatile styling.',
    category: 'luxe',
    price: { amount: 2999, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Signature Luxe Jacket',
    description: 'Signature Luxe Jacket crafted for a refined premium look with elevated detailing, modern tailoring and versatile styling.',
    category: 'luxe',
    price: { amount: 4999, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Premium Textured Polo',
    description: 'Premium Textured Polo crafted for a refined premium look with elevated detailing, modern tailoring and versatile styling.',
    category: 'luxe',
    price: { amount: 2799, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Luxe Black Bomber',
    description: 'Luxe Black Bomber crafted for a refined premium look with elevated detailing, modern tailoring and versatile styling.',
    category: 'luxe',
    price: { amount: 4499, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Premium Resort Shirt',
    description: 'Premium Resort Shirt crafted for a refined premium look with elevated detailing, modern tailoring and versatile styling.',
    category: 'luxe',
    price: { amount: 3299, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Luxury Black Blazer',
    description: 'Luxury Black Blazer crafted for a refined premium look with elevated detailing, modern tailoring and versatile styling.',
    category: 'luxe',
    price: { amount: 4599, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Luxe Blue Blazer',
    description: 'Luxe Blue Blazer crafted for a refined premium look with elevated detailing, modern tailoring and versatile styling.',
    category: 'luxe',
    price: { amount: 4299, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Signature Tailored Suit',
    description: 'Signature Tailored Suit crafted for a refined premium look with elevated detailing, modern tailoring and versatile styling.',
    category: 'luxe',
    price: { amount: 5999, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Black Shirt & Trouser Co-ord',
    description: 'Black Shirt & Trouser Co-ord featuring a coordinated top and bottom combination with a relaxed modern silhouette and effortless styling.',
    category: 'co-ords',
    price: { amount: 3499, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Relaxed Summer Co-ord',
    description: 'Relaxed Summer Co-ord featuring a coordinated top and bottom combination with a relaxed modern silhouette and effortless styling.',
    category: 'co-ords',
    price: { amount: 2999, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Street Utility Co-ord',
    description: 'Street Utility Co-ord featuring a coordinated top and bottom combination with a relaxed modern silhouette and effortless styling.',
    category: 'co-ords',
    price: { amount: 3299, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Monochrome Resort Co-ord',
    description: 'Monochrome Resort Co-ord featuring a coordinated top and bottom combination with a relaxed modern silhouette and effortless styling.',
    category: 'co-ords',
    price: { amount: 3799, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Minimal Beige Co-ord',
    description: 'Minimal Beige Co-ord featuring a coordinated top and bottom combination with a relaxed modern silhouette and effortless styling.',
    category: 'co-ords',
    price: { amount: 3199, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Floral Resort Co-ord',
    description: 'Floral Resort Co-ord featuring a coordinated top and bottom combination with a relaxed modern silhouette and effortless styling.',
    category: 'co-ords',
    price: { amount: 3399, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Clean White Co-ord',
    description: 'Clean White Co-ord featuring a coordinated top and bottom combination with a relaxed modern silhouette and effortless styling.',
    category: 'co-ords',
    price: { amount: 3599, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Holiday Linen Co-ord',
    description: 'Holiday Linen Co-ord featuring a coordinated top and bottom combination with a relaxed modern silhouette and effortless styling.',
    category: 'co-ords',
    price: { amount: 3299, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Urban Night Eau de Parfum',
    description: 'Urban Night Eau de Parfum with a refined fragrance profile, elegant presentation and a premium everyday feel.',
    category: 'perfumes',
    price: { amount: 1999, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Signature Noir Eau de Parfum',
    description: 'Signature Noir Eau de Parfum with a refined fragrance profile, elegant presentation and a premium everyday feel.',
    category: 'perfumes',
    price: { amount: 2299, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Midnight Oud Eau de Parfum',
    description: 'Midnight Oud Eau de Parfum with a refined fragrance profile, elegant presentation and a premium everyday feel.',
    category: 'perfumes',
    price: { amount: 2499, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Fresh Citrus Eau de Parfum',
    description: 'Fresh Citrus Eau de Parfum with a refined fragrance profile, elegant presentation and a premium everyday feel.',
    category: 'perfumes',
    price: { amount: 1799, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Ocean Mist Eau de Parfum',
    description: 'Ocean Mist Eau de Parfum with a refined fragrance profile, elegant presentation and a premium everyday feel.',
    category: 'perfumes',
    price: { amount: 1899, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Velvet Amber Eau de Parfum',
    description: 'Velvet Amber Eau de Parfum with a refined fragrance profile, elegant presentation and a premium everyday feel.',
    category: 'perfumes',
    price: { amount: 2199, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Classic Cologne Eau de Parfum',
    description: 'Classic Cologne Eau de Parfum with a refined fragrance profile, elegant presentation and a premium everyday feel.',
    category: 'perfumes',
    price: { amount: 1999, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  },
  {
    title: 'Pure White Eau de Parfum',
    description: 'Pure White Eau de Parfum with a refined fragrance profile, elegant presentation and a premium everyday feel.',
    category: 'perfumes',
    price: { amount: 1899, currency: 'INR' },
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 4 },
    ],
    images: [],
    published: true,
  }
];